version: '3.9'

networks:
  network:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - network
  lamoda:
    container_name: lamoda
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - network
    depends_on:
      - db
